# # version: '2.0'
#
# # service configuration for our dockerized Rails app
# app:
#
#   # use the Dockerfile next to this file
#   build: .
#
#   # sources environment variable configuration for our app
#   env_file: .env
#
#   # rely on the RAILS_ENV value of the host machine
#   environment:
#     RAILS_ENV: $RAILS_ENV
#
#   # makes the app container aware of the DB container
#   links:
#     db:
#       # use the preferred version of the official Postgres image
#       # see https://hub.docker.com/_/postgres/
#       image: 'postgres:9.4.5'
#
#       # persist the database between containers by storing it in a volume
#       volumes:
#         - 'shortenurl:/home/elihydpc76/shortenUrl'
#
#   # expose the port we configured Unicorn to bind to
#   ports:
#     - "3000:3000"
version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mohan143'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/elihydpc76/shortenUrl'
    env_file:
      - '.env'
volumes:
  postgres:
