# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
#
# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: shortner_prod
#   pool: 5
#   username: b0c4baf3eba144
#   password: eae8aa72
#   host: us-cdbr-iron-east-03.cleardb.net
#   port: 3306
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_HOST_PORT'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEV_DB'] %> #CHANGE ME

test:
  <<: *default
  database: <%= ENV['TEST_DB'] %> #CHANGE ME

production:
  <<: *default
  database:  <%= ENV['PRO_DB'] %>
