# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
#
# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: shortner_prod
#   pool: 5
#   username: b0c4baf3eba144
#   password: eae8aa72
#   host: us-cdbr-iron-east-03.cleardb.net
#   port: 3306
default: &default
  adapter: postgresql
  encoding: unicode
  host: 172.17.0.1
  port: 5433
  pool: 5
  username: postgres
  password: mohan143

development:
  <<: *default
  database: your_dev_db_name #CHANGE ME

test:
  <<: *default
  database: your_test_db_name #CHANGE ME

production:
  <<: *default
  database: your_production_db_name #CHANGE ME
